//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementUserDetail
    {
        public int Id { get; set; }
        public string morderid { get; set; }
        public Nullable<int> mouserid { get; set; }
        public string mname { get; set; }
        public string mphone { get; set; }
        public string morgname { get; set; }
        public string mpostcode { get; set; }
        public string maddress1 { get; set; }
        public string maddress2 { get; set; }
        public string mcity { get; set; }
        public string mcountry { get; set; }
        public string mlandmark { get; set; }
        public string museridemail { get; set; }
    }
}
