//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class agreementbank
    {
        public int Id { get; set; }
        public Nullable<int> agreementid { get; set; }
        public string mbankname { get; set; }
        public string mbankaccount { get; set; }
        public string maccountholder { get; set; }
        public string mbankshort { get; set; }
    }
}
