//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign_user_registration
    {
        public int mcampaignuserid { get; set; }
        public string mfirstname { get; set; }
        public string mlastname { get; set; }
        public string mpostcode { get; set; }
        public string mjobtitle { get; set; }
        public string memailaddress { get; set; }
        public string mphone { get; set; }
        public string morgname { get; set; }
        public string morgregno { get; set; }
        public string mvatno { get; set; }
        public string mstatus { get; set; }
        public Nullable<System.DateTime> mregdate { get; set; }
        public Nullable<System.DateTime> mcreatedate { get; set; }
        public Nullable<int> mschoolid { get; set; }
    }
}
