//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliverystatu
    {
        public int Id { get; set; }
        public Nullable<int> morderid { get; set; }
        public Nullable<int> msubquoteid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<System.DateTime> mreceivedate { get; set; }
        public Nullable<byte> mcondition { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
