//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAgreementView
    {
        public Nullable<int> muserid { get; set; }
        public Nullable<System.DateTime> mest { get; set; }
        public string msorderref { get; set; }
        public Nullable<byte> mpayment { get; set; }
        public int mleaseid { get; set; }
        public Nullable<byte> msend { get; set; }
        public Nullable<double> total { get; set; }
        public string mname { get; set; }
        public Nullable<int> mleaseno { get; set; }
        public Nullable<System.DateTime> mprintdate { get; set; }
        public string morgname { get; set; }
        public string mcity { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> magreementno { get; set; }
        public Nullable<int> morderno { get; set; }
        public string type { get; set; }
        public string mprodname { get; set; }
        public Nullable<double> mprice { get; set; }
        public int msubquoteid { get; set; }
        public Nullable<int> mtermf { get; set; }
        public Nullable<int> mtermp { get; set; }
        public Nullable<double> mvat { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> mprodvarid { get; set; }
        public string mnotes { get; set; }
        public string mstatus { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> msupplierid { get; set; }
        public string menvelopeid { get; set; }
        public string signstatus { get; set; }
        public string town { get; set; }
        public Nullable<byte> minstallationflag { get; set; }
        public string warranty { get; set; }
        public Nullable<int> warrantyterm { get; set; }
        public Nullable<double> warrrantyprice { get; set; }
        public Nullable<int> mdefaultadd { get; set; }
        public Nullable<int> maddress { get; set; }
        public string mmanufacturer { get; set; }
    }
}
