//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class leasedispatchdate
    {
        public int mleasedispatchid { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> Agreementno { get; set; }
        public string dchallan { get; set; }
        public Nullable<System.DateTime> ddispatchdate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> msubquoteid { get; set; }
    }
}
