//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class lessoractivity
    {
        public int mlogid { get; set; }
        public string mactivity { get; set; }
        public Nullable<int> magreement { get; set; }
        public Nullable<int> msupplierid { get; set; }
        public Nullable<System.DateTime> mcreateddate { get; set; }
        public Nullable<int> mcreatedby { get; set; }
    }
}
