//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_master
    {
        public int mluid { get; set; }
        public string museridemail { get; set; }
        public string mpwd { get; set; }
        public string mname { get; set; }
        public string mstatus { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public string musertype { get; set; }
        public Nullable<System.DateTime> mlastlogin { get; set; }
    }
}
