//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailsetting
    {
        public int Id { get; set; }
        public string smtpu { get; set; }
        public string smtpp { get; set; }
        public string host { get; set; }
        public Nullable<byte> enablessl { get; set; }
        public Nullable<int> port { get; set; }
    }
}
