//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsaledeal
    {
        public int msaleid { get; set; }
        public Nullable<int> mprodid { get; set; }
        public Nullable<System.DateTime> msaledatestart { get; set; }
        public Nullable<System.DateTime> msaledateend { get; set; }
        public Nullable<double> msaleprice { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
    }
}
