//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsub
    {
        public int mprodsubid { get; set; }
        public Nullable<int> mprodid { get; set; }
        public string muniquecode { get; set; }
        public string mdescription { get; set; }
        public Nullable<byte> variableproduct { get; set; }
        public Nullable<int> msupplierid { get; set; }
        public Nullable<byte> moresupplier { get; set; }
        public Nullable<int> mleadetime { get; set; }
        public Nullable<byte> noncancellable { get; set; }
        public string mcondition { get; set; }
    }
}
