//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productlease
    {
        public int mproleasetermid { get; set; }
        public Nullable<int> mprodid { get; set; }
        public Nullable<int> mleaseid { get; set; }
        public string mleaseidformula { get; set; }
    }
}
