//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productseo
    {
        public int mproductseoid { get; set; }
        public Nullable<int> mprodid { get; set; }
        public string mtitle { get; set; }
        public string mdescription { get; set; }
        public string mkeywords { get; set; }
        public string mcontents { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
    }
}
