//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productreview
    {
        public int mreviewid { get; set; }
        public Nullable<int> mprodid { get; set; }
        public Nullable<int> mrankno { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<System.DateTime> mreviewdate { get; set; }
        public string mreviewtitle { get; set; }
        public string mcomments { get; set; }
        public Nullable<byte> mactive { get; set; }
    }
}
