//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productaddondetail
    {
        public int Id { get; set; }
        public Nullable<int> maddonprodid { get; set; }
        public Nullable<int> mselecteprod { get; set; }
        public Nullable<int> mcreatedby { get; set; }
        public Nullable<System.DateTime> mcreateddate { get; set; }
        public Nullable<int> msupplier { get; set; }
    }
}
