//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productcat
    {
        public int mprodcatid { get; set; }
        public string mcatname { get; set; }
        public string mcatimage { get; set; }
        public Nullable<int> mpreviouscat { get; set; }
        public Nullable<byte> mfeatured { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<byte> minstallation { get; set; }
        public Nullable<double> mcomission { get; set; }
    }
}
