//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productshiping
    {
        public int mshipid { get; set; }
        public Nullable<int> mprodid { get; set; }
        public string mshippingprovider { get; set; }
        public Nullable<double> mshippingchargeslocal { get; set; }
        public Nullable<double> mshippingchargeszonal { get; set; }
        public Nullable<double> mshippingchargesnational { get; set; }
        public string mprocurementtype { get; set; }
        public Nullable<int> mprocurementdays { get; set; }
    }
}
