//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productweekdeal
    {
        public int mweekid { get; set; }
        public Nullable<int> mprodid { get; set; }
        public Nullable<System.DateTime> mweekstart { get; set; }
        public Nullable<System.DateTime> mweekend { get; set; }
        public Nullable<double> mweekprice { get; set; }
        public Nullable<double> mweekstock { get; set; }
        public Nullable<int> msupplierid { get; set; }
        public Nullable<int> mqty { get; set; }
        public string mofferdetail { get; set; }
        public Nullable<byte> mfeatured { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<byte> mdisctype { get; set; }
    }
}
