//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsubwarrantybysupplier
    {
        public int subwarrantid { get; set; }
        public Nullable<int> warrantyid { get; set; }
        public Nullable<int> warrantyterm { get; set; }
        public Nullable<double> warrantyprice { get; set; }
    }
}
