//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class productwarrantybysupplier
    {
        public int WarrantyId { get; set; }
        public string WarrantyTitle { get; set; }
        public string WarrantyDesc { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Brandid { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<byte> Approve { get; set; }
        public Nullable<byte> Type { get; set; }
        public string DesignedFor { get; set; }
        public string ServiceSupport { get; set; }
        public string ServiceAvailability { get; set; }
        public string WarrantyCode { get; set; }
        public Nullable<byte> Mterm { get; set; }
        public Nullable<int> OCreatedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string Distributor { get; set; }
        public string mmanufacturercode { get; set; }
    }
}
