//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int mprodid { get; set; }
        public string mprodname { get; set; }
        public Nullable<int> mprodregid { get; set; }
        public string mprodregvalue { get; set; }
        public string mpactive { get; set; }
        public Nullable<byte> mfeatured { get; set; }
        public Nullable<byte> mnewarrival { get; set; }
        public Nullable<int> mprodcatid { get; set; }
        public string msearchtags { get; set; }
        public Nullable<int> mbrand { get; set; }
        public string mmanufacturer { get; set; }
        public Nullable<int> mwarrantyterm { get; set; }
        public string mmanufacturerwarrantdesc { get; set; }
        public Nullable<System.DateTime> mmanufacturerdate { get; set; }
        public string mreplacementterm { get; set; }
        public Nullable<int> mreturndays { get; set; }
        public string mreviewed { get; set; }
        public string mquestion { get; set; }
        public Nullable<int> msupplierid { get; set; }
        public string mtaxtype { get; set; }
        public Nullable<double> matxperct { get; set; }
        public Nullable<double> mpriceincltax { get; set; }
        public string mdescription { get; set; }
        public string mprocurementtype { get; set; }
        public string mdraft { get; set; }
        public Nullable<int> mdisplayportal { get; set; }
        public string mpopular { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public string muniquecode { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> papprove { get; set; }
        public Nullable<double> mlengthcm { get; set; }
        public Nullable<double> mdepthcm { get; set; }
        public Nullable<double> mwidthcm { get; set; }
        public Nullable<double> mheightcm { get; set; }
        public Nullable<double> mweightcm { get; set; }
        public Nullable<byte> mweekdeal { get; set; }
        public Nullable<byte> uploadeditapprove { get; set; }
        public Nullable<int> mlessorupload { get; set; }
        public Nullable<int> msupplierwarranty { get; set; }
        public Nullable<int> msupplierwarranty2 { get; set; }
        public Nullable<int> msupplierwarranty3 { get; set; }
        public Nullable<int> msupplierwarranty4 { get; set; }
        public Nullable<int> msupplierwarranty5 { get; set; }
        public string msubsupplier { get; set; }
        public string mmanufacturercode { get; set; }
    }
}
