//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubSupplier
    {
        public int Id { get; set; }
        public Nullable<int> ProdSubId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<double> mrp { get; set; }
        public Nullable<double> mofferprice { get; set; }
        public Nullable<double> msstock { get; set; }
        public Nullable<int> mleadtime { get; set; }
        public string sellerskuid { get; set; }
        public string mactive { get; set; }
        public Nullable<byte> approve { get; set; }
        public Nullable<double> minstallation { get; set; }
        public string resellerskuid { get; set; }
        public string sellername { get; set; }
        public Nullable<double> marginpercentage { get; set; }
        public Nullable<double> sellerrate { get; set; }
        public Nullable<double> RRP { get; set; }
        public string videourl { get; set; }
    }
}
