//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsupplierstatu
    {
        public int Id { get; set; }
        public Nullable<int> SSId { get; set; }
        public Nullable<System.DateTime> KeyDate { get; set; }
        public string KeyNotes { get; set; }
        public Nullable<int> Agno { get; set; }
        public string couriername { get; set; }
        public string trackingnumber { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
    }
}
