//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_bank
    {
        public int msupbankid { get; set; }
        public string mbankname { get; set; }
        public string mbankaddress { get; set; }
        public string maccountname { get; set; }
        public string maccountno { get; set; }
        public string msortcode { get; set; }
        public Nullable<int> msupplierid { get; set; }
    }
}
