//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplieruploadpermit
    {
        public int Id { get; set; }
        public string website { get; set; }
        public Nullable<int> uploadstart { get; set; }
        public Nullable<int> supplierId { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
