//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliercancelorder
    {
        public int mcancelid { get; set; }
        public Nullable<int> msubquoteid { get; set; }
        public Nullable<int> mprodvarid { get; set; }
        public Nullable<int> msupplierid { get; set; }
        public Nullable<double> mvat { get; set; }
        public Nullable<double> mprice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> mtermf { get; set; }
        public Nullable<int> mtermp { get; set; }
        public string mreason { get; set; }
        public Nullable<int> magreementno { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public string mponumber { get; set; }
    }
}
