//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_registration
    {
        public int msuid { get; set; }
        public string museridemail { get; set; }
        public string mpwd { get; set; }
        public string mname { get; set; }
        public string mlname { get; set; }
        public string mphone { get; set; }
        public string morgname { get; set; }
        public string morgregno { get; set; }
        public string mvatno { get; set; }
        public string mpostcode { get; set; }
        public string maddress1 { get; set; }
        public string maddress2 { get; set; }
        public string mcounty { get; set; }
        public string mcity { get; set; }
        public string mcountry { get; set; }
        public string mstatus { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public string musertype { get; set; }
        public Nullable<byte> use_lease { get; set; }
        public Nullable<System.DateTime> laststockupdate { get; set; }
        public string deactivereason { get; set; }
        public string mposition { get; set; }
        public Nullable<System.DateTime> approvedate { get; set; }
        public Nullable<int> msupid { get; set; }
        public Nullable<byte> order_visible { get; set; }
    }
}
