//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_registration_detail
    {
        public int msudid { get; set; }
        public Nullable<int> msuid { get; set; }
        public string morgregno { get; set; }
        public Nullable<byte> use_lease { get; set; }
        public string website { get; set; }
        public string source_enquiry { get; set; }
        public string trading_as { get; set; }
        public Nullable<System.DateTime> date_established { get; set; }
        public string target_places { get; set; }
        public Nullable<byte> com_type { get; set; }
        public string com_logo { get; set; }
        public string owner { get; set; }
        public string com_email { get; set; }
        public string mcatlist { get; set; }
    }
}
