//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_more
    {
        public int supplier_more_id { get; set; }
        public Nullable<int> supplierid { get; set; }
        public string monthly_sales { get; set; }
        public string monthly_lease { get; set; }
        public string msalespeople { get; set; }
        public string moldleasename { get; set; }
        public string mfacilties { get; set; }
        public string mencourage { get; set; }
        public Nullable<int> proposal { get; set; }
        public string moffer { get; set; }
        public string mother { get; set; }
    }
}
