//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_contacts
    {
        public int supplier_contact_id { get; set; }
        public Nullable<int> supplierid { get; set; }
        public string susername { get; set; }
        public string sposition { get; set; }
        public string semailaddress { get; set; }
        public string sphone { get; set; }
    }
}
