//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_users_rights
    {
        public int msupuserrightid { get; set; }
        public Nullable<int> msupuserid { get; set; }
        public string mmodule { get; set; }
        public string mrights { get; set; }
    }
}
