//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_equipment
    {
        public int supplier_equipment_id { get; set; }
        public Nullable<int> supplierid { get; set; }
        public string equipment_sold { get; set; }
        public string equipment_brand { get; set; }
        public Nullable<double> warrantly_length { get; set; }
        public string warrranty_provider { get; set; }
    }
}
