//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_banner
    {
        public int Id { get; set; }
        public string banner_img { get; set; }
        public string banner_link { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> last_update_date { get; set; }
        public Nullable<int> last_update_by { get; set; }
    }
}
