//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string ReplyEmail { get; set; }
        public string Mobile { get; set; }
        public string Department { get; set; }
        public string Subject { get; set; }
        public string Detail { get; set; }
        public string Priority { get; set; }
        public string Attachment { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModify { get; set; }
        public string Type { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string ModuleType { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
