//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKSchool
    {
        public int id { get; set; }
        public string LocalAuthority { get; set; }
        public string SchoolName { get; set; }
        public string SchoolType { get; set; }
        public Nullable<int> SchoolTypeGroup { get; set; }
        public Nullable<int> SchoolPhase { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public Nullable<int> Pupils { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls { get; set; }
        public string TrustSchool { get; set; }
        public string updateDate { get; set; }
        public string Street { get; set; }
        public string Locality { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
        public string www { get; set; }
        public string telephone { get; set; }
        public string HeadTitle { get; set; }
        public string HeadFirstName { get; set; }
        public string HeadLastName { get; set; }
        public string JobTitle { get; set; }
        public string DistrictAminstartive { get; set; }
        public string OfstedRating { get; set; }
        public string RSCRegion { get; set; }
        public string Addressline3 { get; set; }
        public string TrustName { get; set; }
    }
}
