//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class userordermaster
    {
        public int morderid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<int> morderref { get; set; }
        public string msorderref { get; set; }
        public string morderstatus { get; set; }
        public string mprodlist { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string mnotes { get; set; }
    }
}
