//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_contact_more
    {
        public int Id { get; set; }
        public Nullable<int> usermoreid { get; set; }
        public string cusername { get; set; }
        public string csurname { get; set; }
        public string cposition { get; set; }
        public string cemailaddress { get; set; }
        public string cphone { get; set; }
        public Nullable<byte> cdefault { get; set; }
    }
}
