//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_registration_more
    {
        public int musermoreid { get; set; }
        public Nullable<int> muid { get; set; }
        public string mphone { get; set; }
        public string morgname { get; set; }
        public string morgregno { get; set; }
        public string mvatno { get; set; }
        public string mleasestatus { get; set; }
        public Nullable<System.DateTime> mregdate { get; set; }
        public Nullable<int> mschoolid { get; set; }
    }
}
