//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersubquotationwarranty
    {
        public int msubquotewarrantid { get; set; }
        public Nullable<int> msubquoteid { get; set; }
        public string mprodname { get; set; }
        public Nullable<double> mvat { get; set; }
        public Nullable<double> mprice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> mtermf { get; set; }
        public Nullable<int> mtermp { get; set; }
        public Nullable<int> msubwarrantid { get; set; }
    }
}
