//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class userleaseagreement
    {
        public int mleaseid { get; set; }
        public Nullable<int> muserid { get; set; }
        public Nullable<int> mleaseno { get; set; }
        public Nullable<double> ffee { get; set; }
        public Nullable<double> sfee { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public string mprintby { get; set; }
        public Nullable<System.DateTime> mprintdate { get; set; }
        public Nullable<byte> msend { get; set; }
        public Nullable<System.DateTime> mdocdate { get; set; }
        public string mlessorno { get; set; }
        public string msorderref { get; set; }
        public Nullable<byte> mpayment { get; set; }
        public Nullable<System.DateTime> mest { get; set; }
        public Nullable<int> mcontactid { get; set; }
        public Nullable<int> mdefaultadd { get; set; }
        public Nullable<System.DateTime> mactualdelivery { get; set; }
        public string menvelopeid { get; set; }
        public string mstatus { get; set; }
        public string magstatus { get; set; }
        public Nullable<int> mtrno { get; set; }
    }
}
