//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_registration_addr
    {
        public int museraddrid { get; set; }
        public Nullable<int> muid { get; set; }
        public string mpostcode { get; set; }
        public string maddress1 { get; set; }
        public string maddress2 { get; set; }
        public string mcity { get; set; }
        public Nullable<int> mcountry { get; set; }
        public string mlandmark { get; set; }
        public string maddresstype { get; set; }
    }
}
