//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersubquotation
    {
        public int msubquoteid { get; set; }
        public Nullable<int> mquoteid { get; set; }
        public Nullable<int> mprodvarid { get; set; }
        public Nullable<int> msupplierid { get; set; }
        public Nullable<double> mvat { get; set; }
        public Nullable<double> mprice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> mtermf { get; set; }
        public Nullable<int> mtermp { get; set; }
        public string mstatus { get; set; }
        public string type { get; set; }
        public string mnotes { get; set; }
        public Nullable<int> mapproveby { get; set; }
        public Nullable<byte> mflexible { get; set; }
        public Nullable<int> morderno { get; set; }
        public Nullable<int> magreementno { get; set; }
        public Nullable<byte> mnotifyflag { get; set; }
        public string mofferdetail { get; set; }
        public Nullable<System.DateTime> mexpdeliverydate { get; set; }
        public Nullable<byte> msendtosupplier { get; set; }
        public Nullable<byte> order_visible { get; set; }
        public Nullable<byte> minstallationflag { get; set; }
        public Nullable<double> sellerrate { get; set; }
        public Nullable<double> ourrate { get; set; }
    }
}
