//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingPortalApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class userquotationmaster
    {
        public int mquoteid { get; set; }
        public Nullable<int> muserid { get; set; }
        public string mquoteref { get; set; }
        public Nullable<double> mquotetotal { get; set; }
        public string mquotestatus { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
